name: Keep Server Alive

on:
  schedule:
    # Run every 12 minutes (cron format: minute hour day month weekday)
    - cron: '*/12 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Server
        run: |
          echo "Pinging server to keep it alive..."
          curl -f https://vit-api-ca7a.onrender.com/health || echo "Server might be starting up..."
          
      - name: Log Status
        run: |
          echo "Keep-alive ping completed at $(date)"
